name: Run DreamO Model

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check disk space before cleanup
      run: df -h

    - name: Clean apt cache and remove temp files to free space
      run: |
        sudo apt-get clean
        rm -rf /tmp/*
        rm -rf ~/.cache/huggingface

    - name: Check disk space after cleanup
      run: df -h

    - name: Run script
      run: python app.py  # change this if your entry point is different

    - name: Check disk space after script
      run: df -h
