name: dream0

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run app.py with Hugging Face token
        env:
          HF_HOME: ${{ runner.temp }}/hf_cache
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HUGGINGFACE_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python app.py
