name: Run DreamO Model

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Free up disk space
      run: |
        sudo apt-get clean
        rm -rf /tmp/* || true
        rm -rf ~/.cache/huggingface || true

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: |
        python app.py  # change this if your entry point is different
